title: "〜超初心者向け〜個人アプリにRSpecを書いてみよう！！"
summary: "こちらは在籍しているプログラミングスクール内のハンズオンイベントにて使用するために作成した本になります。\nイベントに参加していなくてもこちらの本1冊のみで簡単にRSpecが書ける構成にしています。"
topics: ["ruby", "rails", "rspec"]
published: false
price: 0